#create new schema
#DROP SCHEMA r3ise;
CREATE SCHEMA IF NOT EXISTS r3ise;
USE r3ise;

#create staff table
CREATE TABLE STAFF(
Nric VARCHAR(9) NOT NULL PRIMARY KEY,
Salutation VARCHAR(4) NOT NULL,
Name VARCHAR(255) NOT NULL,
PasswordHash VARCHAR(255) NOT NULL,
Salt VARCHAR(255) NOT NULL,
Last_Updated DATE NOT NULL
);

#create users table
CREATE TABLE USERS(
Nric VARCHAR(9) NOT NULL PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
`Class` VARCHAR(255) NOT NULL,
`Group` VARCHAR(255) NOT NULL
);

#create transaction_details table
CREATE TABLE TRANSACTION_DETAILS(
Staff VARCHAR(9) NOT NULL,
`User` VARCHAR(9) NOT NULL,
Delta INT NOT NULL,
Reason VARCHAR(255),
Transaction_DateTime DATETIME NOT NULL,
CONSTRAINT TRANSACTION_DETAILS_PK PRIMARY KEY (Staff,`User`,Transaction_DateTime),
CONSTRAINT TRANSACTION_DETAILS_FK1 FOREIGN KEY (Staff) REFERENCES STAFF(Nric),
CONSTRAINT TRANSACTION_DETAILS_FK2 FOREIGN KEY (`User`) REFERENCES USERS(Nric)
);